version: '3.8'

services:
  service-a:
    image: beriloqueiroz/desafio-tracing-distribuido-span-a:latest
    build: 
      context: ./service_A
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - otel-collector

  service-b:
    image: beriloqueiroz/desafio-tracing-distribuido-span-b:latest
    build: 
      context: ./service_B
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686" # port to access by browser
      - "14268"
      - "14250"