receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

extensions:
  health_check: {}

exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9090

processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, prometheus]
