receivers:
  otlp:
    protocols:
      http:

extensions:
  health_check: {}

exporters:
  # otlp:
  #   endpoint: jaeger-all-in-one:4317
  #   tls:
  #     insecure: true

  otlp:
    endpoint: http://zipkin-all-in-one:9411
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9090

processors:
  batch:
    timeout: 30s
    send_batch_size: 1

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, prometheus]
